export { BsChevronDown as DropdownIcon } from 'react-icons/bs';
export { default as EditIcon } from './EditIcon';
export { default as InfoIcon } from './InfoIcon';
export { default as SearchIcon } from './SearchIcon';
export { default as UploadIcon } from './UploadIcon';
export { SlTrash as TrashIcon } from 'react-icons/sl';
export { CiPause1 as PauseIcon, CiPlay1 as StopIcon } from 'react-icons/ci';
export { FaPlay as PlayIcon } from 'react-icons/fa';
export { AiOutlinePlus as PlusIcon, AiOutlineMinus as MinusIcon } from 'react-icons/ai';
export { IoMdClose as CloseIcon } from 'react-icons/io';
export * from './SignatureIcon';
export * from './DownloadIcon';